### ISSUE TITLE
Starting nadda doesn't work

### ISSUE THREAD

**Issue by whatda** [iamcdonald/nadda#1]
Hi,

When trying to start nadda via cli (git bash under windows) with

`nadda -f ~/code/frontend-tests/features/*.feature -s ~/code/frontend-tests/steps/*.js
Starting selenium server... started - PID:  5252`

I get the following error:

`Cannot read source folder: C:\Users\mya\code\C:\Users\mya\AppData\Roaming\npm\node_modules\nadda\lib\sandbox\features`

I've tried different variants of the paths, but none worked.

Trying to start it programmatically returns the following error:

```
Starting selenium server... started - PID:  1196
INFO Selenium process finished.

Error: Cannot find module 'C:\Users
yacode
ode_modules
addalib\utils\decode-feature'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\mya\code\node_modules\nadda\lib\sandbox\
features\frontend-tests\features\Feature.js:4:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

nightwatch alone works fine.

What could I try?

**Comment by iamcdonald** [comment]
Hi,

just wondering if you've globally installed nadda?
If so it looks like the internal paths used within nadda are getting tripped up by this.

**Comment by whatda** [comment]
Hi,

yes I have done so. Shouldn't I? I just tried to use the cli like in the docs, so I assumed I need to install it globally.

**Comment by iamcdonald** [comment]
Yeah, that's true.
That's a misnomer in the docs on my part, sorry dude.

I usually install npm packages locally within repo's that need them.
That way anyone can pull down the repo and npm install will get all required dependecies for dev (testing, serving etc.). 

However, as you've pointed out that precludes being able to just run ```nadda ...```.

If you install it locally, and then alias it through an npm script and provide relative paths to your features and steps that should get you up and running for now. Please let me know if that still doesn't work for you or if you need extra clarification. 

In the mean time I'll look into what I need to do in order to allow nadda to be installed and used globally.

Sorry again.

**Comment by iamcdonald** [comment]
Hi @whatda,

I've just pushed a new version of nada to npm (0.6.0) which should fix the issue of not being able to run from a global install. There are a couple of gotcha's that I've added to the readme but other than that it should work fine.

If you have a chance to try it out please let me know cause I'd rather wait till it's been corroborated as fixed on another machine/OS before closing the issue.

Thanks again for raising it,

Iain

**Comment by whatda** [comment]
Hey Iain,

thanks for your reply! I'll try it out next week and then post my results here.

**Comment by iamcdonald** [comment]
Much appreciated, thanks.

**Comment by whatda** [comment]
Sorry, but it's still not working. :(

Doesn't matter if I use the local or global nadda.

`$ node_modules/nadda/bin/nadda -f './frontend-tests/features/*.feature' -s './frontend-tests/steps/*.js'`

outputs

`Selenium server is not running.`

`Cannot read source folder: C:\Users\mya\code\C:\Users\mya\code\node_modules\nadda\lib\sandbox\features`

Using v0.6.0, for both the local and global version.

**Comment by iamcdonald** [comment]
Ah, I assume it's because the pathing is different on windows.

Basically nightwatch assumes that the source folder will always be relative to process.cwd()
and if it can't find it in the path given for your test source folder it prepends it.

Which means I need to prepend a bunch of `../`  to the path passed to nightwatch in order to mitigate it.

However, it looks like I'll need to find a more robust way to do so.
I'll take another look at it this evening.

**Comment by whatda** [comment]
Okay, thanks a lot!

Just an idea: Maybe a nadda.json with paths (relative to it's location) would be simpler than having to specify the paths directly on each invocation.

**Comment by iamcdonald** [comment]
Hi again,

I've pushed something up that I'm hoping will work on Windows too. Unfortunately I don't have access to a  windows machine. Rather than doing another release would you be able to clone this repo and run the tests (should just need to run ```npm install``` and then ```npm test```). You'll need to make sure you've uninstalled nadda globally before running the tests as selenium/drivers seem to get themselves in a bit of twist.

I know it's a bit of an ask but it's sort of the only way I have of testing it on Windows, apologies.

With regards to the nadda.json that should be fairly easy to implement and yeah it makes sense rather than having to specify the same things over and over again.

**Comment by whatda** [comment]
Thank you for your work. I did `npm uninstall -g nadda`, cloned the repo into it's own directory, performed `npm install` and `npm test`. The latter outputs the following:

```
No coverage information was collected, exit without writing coverage information
C:\Users\mya\code\nadda\node_modules\.bin\_mocha.CMD:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                              ^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\mya\code\nadda\node_modules\istanbul\lib\hook.js:109:37)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at runFn (C:\Users\mya\code\nadda\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
    at C:\Users\mya\code\nadda\node_modules\istanbul\lib\command\common\run-with-cover.js:251:17
    at C:\Users\mya\code\nadda\node_modules\istanbul\lib\util\file-matcher.js:68:16

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "unit_tests"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! nadda@0.6.0 unit_tests: `istanbul cover _mocha -- -R spec --recursive tests/unit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nadda@0.6.0 unit_tests script 'istanbul cover _mocha -- -R spec --recursive tests/unit'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nadda package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     istanbul cover _mocha -- -R spec --recursive tests/unit
npm ERR! You can get their info via:
npm ERR!     npm owner ls nadda
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mya\code\nadda\npm-debug.log
npm ERR! Test failed.  See above for more details.
```

**Comment by iamcdonald** [comment]
From what I can see that looks like it's probably related to [this](https://github.com/gotwarlost/istanbul#usage-on-windows) on istanbul which is being used for code coverage.

I've followed the tips on there and pushed that up to the repo.
If you could pull down the changes and re-run the tests hopefully we'll get a little further.

**Comment by whatda** [comment]
Now some assertions are failing. From what I see it's because of the path structure:

```
+ expected - actual

      -C:\sandbox\nightwatch.json
      +/sandbox/nightwatch.json
```

**Comment by iamcdonald** [comment]
I'll need to go through the tests tonight and use ```path.resolve``` anywhere asserting a path. Sorry again about this.

Just out of interest in the mean time can you just run ```npm run e2e_tests```? This should skip the rest of the tests and only run those testing the full end to end usage of nadda.

**Comment by whatda** [comment]
That leaves me with a `Cannot read source folder: C:\C:\Users\mya\code\nadda\lib\sandbox\features`

**Comment by iamcdonald** [comment]
So close. 
Just pushed another change if you want to pull that and try ```npm run e2e_tests``` again.

**Comment by whatda** [comment]
Same error.

**Comment by iamcdonald** [comment]
Bohgus.
Just pushed up another change.
This time you'll need to refresh the npm dependencies
 ```rm -rf ./node_modules && npm cache clean && npm install``` (if yr using git for windows/git bash should work. Basically just deleting the node_modules folder and clearing npm's cache then re-installing the dependencies) 

I'm hopeful you should be able to get to running the tests now. 
Hopefully that's the only hurdle, in which case I can push out a new version.

**Comment by whatda** [comment]
Sorry, it's still not working.

`npm run e2e_tests`

```
Starting selenium server... started - PID:  4044

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at new Module (C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\module.js:7:23)
    at new TestSuite (C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\testsuite.js:17:17)
    at runTestModule (C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\run.js:38:19)
    at runNextModule (C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\run.js:191:23)
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\run.js:227:9
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\run.js:159:9
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\walk.js:139:9
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\walk.js:67:17
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\walk.js:67:17
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\walk.js:67:17
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\walk.js:67:17
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\walk.js:67:17
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\walk.js:67:17
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\walk.js:76:13
    at FSReqWrap.oncomplete (fs.js:82:15)

    1) should run the features correctly
INFO Selenium process finished.
```

**Comment by iamcdonald** [comment]
I guess it's a small mercy that at least we're past the initial problem.

It looks from the logs like Windows ids being tripped up by some of the requires that are happening in order to run the tests. 

I've pushed up something which I'm hoping will deal with that but I've also scattered in some logging around where I think it might be tripping up in order to try and get a better understanding.

You should be able to just pull down the changes and re-run the e2e tests.
I think we're getting close though.

**Comment by whatda** [comment]
```
$ npm run e2e_tests

> nadda@0.6.0 e2e_tests C:\Users\mya\code\nadda
> mocha -R spec --recursive tests/e2e



  nadda e2e
Starting selenium server... started - PID:  8356

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at new Module (C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\module.js:7:23)
    at new TestSuite (C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\testsuite.js:17:17)
    at runTestModule (C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\run.js:38:19)
    at runNextModule (C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\run.js:191:23)
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\run.js:227:9
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\run.js:159:9
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\walk.js:139:9
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\walk.js:67:17
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\walk.js:67:17
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\walk.js:67:17
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\walk.js:67:17
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\walk.js:67:17
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\walk.js:67:17
    at C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\walk.js:76:13
    at FSReqWrap.oncomplete (fs.js:82:15)

    1) should run the features correctly
INFO Selenium process finished.
```

**Comment by iamcdonald** [comment]
Ok, so if that's the same it's bailing somewhere in nightwatch. Specifically when it tries to require in a module to test (C:\Users\mya\code\nadda\node_modules\nightwatch\lib\runner\module.js:7). If you could stick a line above that (within nightwatch) to console.log out the modulePath it's trying to require we could try and work back from that?

**Comment by whatda** [comment]
modulePath:
`C:\Users\mya\code\nadda\lib\sandbox\features\tests\e2e\lib\fixture\features\duckduckgo-search\duckduckgo-search`

**Comment by iamcdonald** [comment]
Weird.
I'm assume it's bailing [here](https://github.com/iamcdonald/nadda/blob/master/lib/utils/create-steps-lib.js#L15) I'm just not sure why we aren't seeing any of the console logs I put in.

**Comment by iamcdonald** [comment]
I assume it bailing [here](https://github.com/iamcdonald/nadda/blob/master/lib/utils/create-steps-lib.js#L15) I just can't see why it's not logging anything out from the line above.
could you comment that line 15 out and see if that is in fact the cause of this error?

**Comment by whatda** [comment]
I still get the same error after commenting out that line.

**Comment by iamcdonald** [comment]
I thin we've gone down this remote-debugging road as far as we can. I'm going to try and get a hold of a windows machine or windows VM over the weekend and go through this locally to work out what it is that's causing the issue.

Sorry it's taken so long to resolve but hopefully I'll have solution by next week.

**Comment by whatda** [comment]
Thanks for your efforts!

**Comment by iamcdonald** [comment]
Hi again @whatda,
sorry this has taken a while.
I've pushed up a change to the repo that get's past all the previous errors but selenium bails.
However, I'm thinking that might be to do with the VM I have of windows and not having the right version of java installed or not installed in the right way.

Anyway, I was wondering if you could pull the changes in again and try re running the e2e tests?

**Comment by whatda** [comment]
Hi @iamcdonald,
Now the other errors don't show up anymore, but instead I get:

`Connection refused! Is selenium server started?`

**Comment by iamcdonald** [comment]
Sorry for the late reply. I'm afraid I'm at a loss. 

The current state of play is that nightwatch fires up selenium and after a while I get a selenium error saying that there is already something running on port 4444. I don't suppose you have a sample project using just nightwatch that I'd be able to pull down onto the virtual machine just to check that it isn't some setup aspect of the windows VM.

**Comment by iamcdonald** [comment]
Hey @whatda,
 
So it seems I spoke just too soon. The latest works now although running the e2e_tests doesn't for some reason. 
However if you pull it down the latest and, whilst within the nadda folder, run 
```
npm install . -g
```
and then
```
nadda -f 'tests/e2e/lib/fixture/**/*.feature' -s 'tests/e2e/lib/fixture/**/*.steps.js'  -l ENGLISH -c tests/e2e/lib/fixture/nightwatch.json -e CHROME
```
you should hopefully see the tests being ran in chrome.
Certainly it's working for me within the windows VM.

I'm sure by this point you'd probably given up all hope of this ever working and have moved on. However, if you get a chance to run the above and could let me know how you get in it would be much appreciated.

Thanks again.

**Comment by whatda** [comment]
Hi @iamcdonald 

Yes, you're right. We've chosen to stay with just nightwatch for now, but that might change in the future.

Thanks for your efforts, the above is definitely working! I just tested it.

**Comment by iamcdonald** [comment]
No worries @whatda, 
thanks for sanity checking the fix again for me though, much appreciated.
New build's just been published to npm - 0.6.1.
